# Generated by Django 5.1.3 on 2024-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predication', '0003_remove_customer_id_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
